# Generated by Django 5.0.1 on 2024-02-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(default='-')),
                ('times_edited', models.IntegerField()),
                ('last_edited', models.DateField()),
                ('reqd_values', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuantifiedSelf.trackertype', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField()),
                ('value', models.CharField(max_length=128)),
                ('note', models.TextField()),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='QuantifiedSelf.tracker')),
            ],
        ),
    ]
