# Generated by Django 5.0.1 on 2024-02-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuantifiedSelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='user_id',
            new_name='user',
        ),
    ]
