# Generated by Django 5.0.1 on 2024-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuantifiedSelf', '0002_rename_user_id_tracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='reqd_values',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='times_edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trackerlogs',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
